[tool.poetry]
name = "olas-operate-middleware"
version = "0.1.0-rc127"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
packages = [
    { include = "operate" }
]
include = [
    "operate/data/acn/*",
    "operate/data/contracts/*",
    "operate/data/contracts/service_staking_token/*",
    "operate/data/contracts/service_staking_token/build/*",
]

[tool.poetry.scripts]
operate = "operate.cli:main"


[tool.poetry.dependencies]
python = "<3.13,>=3.9"
py-multibase = "==1.0.3"
py-multicodec = "==0.2.1"
py-eth-sig-utils = "*"
aiohttp = "<4.0.0,>=3.8.5"
open-autonomy = "==0.14.12"
multidict = "*"
open-aea-ledger-ethereum = "==1.52.0"
open-aea-ledger-cosmos = "==1.52.0"
open-aea-ledger-ethereum-flashbots = "==1.52.0"
open-aea-cli-ipfs = "==1.52.0"
openapi-core = "==0.15.0"
openapi-spec-validator = "<0.5.0,>=0.4.0"
clea = "==0.1.0rc4"
cytoolz = "==0.12.3"
grpcio = "==1.53.0"
asn1crypto = "<1.5.0,>=1.4.0"
protobuf = "<4.25.0,>=4.21.6"
docker = "6.1.2"
fastapi = "==0.110.0"
eth-hash = "==0.7.0"
eth-account = "==0.8.0"
eth-keyfile = "==0.6.1"
eth-keys = "==0.4.0"
eth-rlp = "==0.3.0"
eth_typing = "*"
eth-utils = "==2.2.0"
eth-abi = "==4.0.0"
frozenlist = "==1.4.1"
hexbytes = "==0.3.1"
ipfshttpclient = "==0.8.0a2"
jsonschema = "<4.4.0,>=4.3.0"
requests = "==2.28.1"
requests-toolbelt = "1.0.0"
starlette = "==0.36.3"
uvicorn = "==0.27.0"
web3 = "<7,>=6.0.0"
psutil = "^5.9.8"
pyinstaller = "^6.8.0"
urllib3 = "==1.26.16"
pycryptodome = "==3.18.0"
packaging = "*"
certifi = "==2021.10.8"
hypothesis = "==6.21.6"
open-aea-test-autonomy = "==0.14.12"
py-ecc = "==6.0.0"
pytz = "==2022.2.1"
typing_extensions = ">=3.10.0.2"
websocket_client = "<1,>=0.32.0"
toml = "==0.10.2"
pytest-asyncio = "*"
pytest = "==7.2.1"

















[tool.poetry.group.development.dependencies]
tomte = {version = "0.2.17", extras = ["cli"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
