name: "Test Pearl Installation E2E"
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  e2e-test:
    continue-on-error: False

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, macos-14]

    timeout-minutes: 30

    steps:

    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
          node-version: "20.11"

    - name: Remove brew
      if: runner.os == 'macOS'
      run:  |
        yarn
        # Uninstall brew
        sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

    - name: Install node dependencies
      run: yarn install

    - name: Run Test
      run: |
        node electron/test.js