name: "Integration tests"
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  integration-test:
    continue-on-error: False

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, macos-14]
        python-version: [3.10, 3.11, 3.12]

    timeout-minutes: 30

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        submodules: recursive
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Test
      run: |
        pytest -s tests