name: "Integration tests"
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  integration-test:
    continue-on-error: False

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, macos-14]
        python-version: ["3.10", "3.11", "3.12"]

    timeout-minutes: 30

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        submodules: recursive
        python-version: ${{ matrix.python-version }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ matrix.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Check if dependencies can be locked
      run: poetry lock --check

    - name: Poetry install requirements
      run: poetry install --all-extras --no-interaction -vvv

    - name: Run Test
      run: |
        source $(poetry env info --path)/bin/activate
        pytest -s tests