name: Release

# Triggered on pushing a tag
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # PyInstaller job for both x64 and arm64 binaries
  build-macos-pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-14-large]

    steps:
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Poetry and its dependencies
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.4.0"
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      # Set architecture for macos-latest-large as x64 and arm64 for other versions
      - name: Set architecture environment variable
        run: |
          if [ "${{ matrix.os }}" == "macos-14-large" ]; then echo "OS_ARCH=x64" >> $GITHUB_ENV; else echo "OS_ARCH=arm64" >> $GITHUB_ENV; fi

      # Cache Poetry dependencies with unique key for each environment and architecture
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            ~/.venv
          key: poetry-${{ env.OS_ARCH }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ env.OS_ARCH }}-

      - name: Install dependencies
        run: poetry install

      # Download and build with PyInstaller
      - name: Get trader bin
        run: |
          trader_version=$(poetry run python -c "import yaml; config = yaml.safe_load(open('templates/trader.yaml')); print(config['service_version'])")
          echo $trader_version
          mkdir dist && curl -L -o dist/aea_bin "https://github.com/valory-xyz/trader/releases/download/${trader_version}/trader_bin_${{ env.OS_ARCH }}"

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller operate/services/utils/tendermint.py --onefile
          poetry run pyinstaller --collect-data eth_account --collect-all aea --collect-all autonomy --collect-all operate --collect-all aea_ledger_ethereum --collect-all aea_ledger_cosmos --collect-all aea_ledger_ethereum_flashbots --hidden-import aea_ledger_ethereum --hidden-import aea_ledger_cosmos --hidden-import aea_ledger_ethereum_flashbots operate/pearl.py --add-binary dist/aea_bin:. --add-binary dist/tendermint:. --onefile --name pearl_${{ env.OS_ARCH }}

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4
        with:
          name: pearl_${{ env.OS_ARCH }}
          path: dist/pearl_${{ env.OS_ARCH }}

  # Jobs for production and development, running separately for x64 and arm64
  build-release:
    runs-on: macos-latest
    strategy:
      matrix:
        env: [production, development]
        include:
          - env: production
            rpc: https://rpc-gate.autonolas.tech/gnosis-rpc/
          - env: development
            rpc: https://virtual.gnosis.rpc.tenderly.co/78ca845d-2b24-44a6-9ce2-869a979e8b5b

    needs: build-macos-pyinstaller

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pearl_x64
          path: electron/bins/
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pearl_arm64
          path: electron/bins/
      
      - name: Read directory
        run: ls -R electron/bins/

      - name: Add exec permissions
        run: chmod +x electron/bins/pearl_x64 && chmod +x electron/bins/pearl_arm64

      # Cache node_modules with unique key for each environment and architecture
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            frontend/node_modules
          key: ${{runner.os}}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # Install dependencies
      - name: Install dependencies
        run: |
          yarn install
          yarn install:frontend

      # Build frontend for production
      - name: Build frontend
        run: yarn build:frontend
        env:
          NODE_ENV: ${{ matrix.env }}
          DEV_RPC: ${{ matrix.rpc }}
          IS_STAGING: ${{ github.ref != 'refs/heads/main' && 'true' || 'false' }}
          FORK_URL: ${{ matrix.rpc }}

      # Run the build and notarization process for production
      - name: Build, notarize, and publish
        env:
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
          APPLE_ID: ${{ secrets.APPLEID }}
          APPLETEAMID: ${{ secrets.APPLETEAMID }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.github_token }}
          NODE_ENV: ${{ matrix.env }}
          DEV_RPC: ${{ matrix.rpc }}
          FORK_URL: ${{ matrix.rpc }}
        run: node build.js
